from element.Dept_E import Dept_E
class Dept_B(Dept_E):
	def add_Dept(self,sleepTime10,sleepTime12,DeptName,sleepTime1,SupperDeptName,sleepTime11,DeptNo,DeptShotName,DeptLeader,sleepTime2,sleepTime3):
		self.clickSysNav()
		self.WaitTime(sleepTime10)
		self.clickDataCenter()
		self.waitSysManVisible()
		self.clickSys()
		self.clickDept()
		self.WaitTime(sleepTime12)
		self.clickAddButton()
		self.sendDeptName(DeptName)
		self.sendDeptType()
		self.WaitTime(sleepTime1)
		self.sendDeptTypeValue()
		self.clickSupperDept()
		self.sendSupperDeptName(SupperDeptName)
		self.WaitTime(sleepTime11)
		self.clickSupperDeptValue()
		self.sendDeptNo(DeptNo)
		self.sendDeptShotName(DeptShotName)
		self.sendDeptLeader(DeptLeader)
		self.WaitTime(sleepTime2)
		self.clickSaveButton()
		self.WaitTime(sleepTime3)
	def search_Dept(self,DeptName,sleepTime4,sleepTime5,IsDeptName):
		self.sendSearchKey(DeptName)
		self.WaitTime(sleepTime4)
		self.clickSearchButton()
		self.WaitTime(sleepTime5)
		self.assertDeptName(IsDeptName)
	def alter_Dept(self,DeptName,sleepTime6,IsDeptName):
		self.clickAlterButton()
		self.clearDeptName()
		self.alterDeptName(DeptName)
		self.clickSaveButton()
		self.WaitTime(sleepTime6)
		self.assertDeptName(IsDeptName)
	def del_Dept(self,sleepTime7,sleepTime8):
		self.clickDelButton()
		self.WaitTime(sleepTime7)
		self.clickConfirmButton()
		self.WaitTime(sleepTime8)
	